const initialState = {
  company: "",
  first_name: "",
  last_name: "",
  address_1: "",
  address_2: "",
  city: "",
  country_code: "",
  province: "",
  postal_code: "",
  phone: "",
  email: "",
  billing_company: "",
  billing_first_name: "",
  billing_last_name: "",
  billing_address_1: "",
  billing_address_2: "",
  billing_city: "",
  billing_country_code: "",
  billing_province: "",
  billing_postal_code: "",
  billing_phone: "",
  same_as_shipping: true,
  discountCode: "",
};
export { initialState };
